using System.Text.Json;
using TracezillaShopify.Shopify; using TracezillaShopify.Tracezilla;
namespace TracezillaShopify.Workflows;
public sealed record SkuCreationItem(string SourceId,string? Sku,string Status,string Message);
public sealed record SkuCreationResult(object Summary,IReadOnlyList<SkuCreationItem> Items,int FailedCount);
public sealed class CreateTracezillaSkus(ShopifyCatalogService source,TracezillaCatalogService target)
{
 public async Task<SkuCreationResult> RunAsync(bool dryRun=true,int limit=10){if(limit<1)throw new ArgumentOutOfRangeException(nameof(limit));var variants=await source.ReadVariantsAsync();var existing=(await target.ExistingSkuCodesAsync()).ToHashSet(StringComparer.Ordinal);var seen=new HashSet<string>();var items=new List<SkuCreationItem>();foreach(var value in variants.Take(limit)){var id=value.TryGetProperty("id",out var idv)?idv.GetString()??"unknown":"unknown";var sku=value.TryGetProperty("sku",out var sv)?sv.GetString()?.Trim():null;if(string.IsNullOrEmpty(sku)){items.Add(new(id,null,"invalid","Shopify variant does not have an SKU."));continue;}if(existing.Contains(sku)){items.Add(new(id,sku,"skipped","SKU already exists in tracezilla."));continue;}if(!seen.Add(sku)){items.Add(new(id,sku,"skipped","Another Shopify variant in this run has the same SKU."));continue;}var payload=new{sku_code=sku,global_name=sku,weight_factor_net=1.0,weight_factor_gross=1.0,unit_of_measure="pcs",lot_unit="colli",default_uom_conversion=1.0};if(dryRun)items.Add(new(id,sku,"would_create","SKU would be created during execution."));else try{await target.CreateSkuAsync(payload);existing.Add(sku);items.Add(new(id,sku,"created","SKU was created in tracezilla."));}catch{items.Add(new(id,sku,"failed","tracezilla rejected the SKU creation request."));}}
 int Count(string s)=>items.Count(x=>x.Status==s);var failed=Count("failed");return new(new{source_count=variants.Count,selected_count=Math.Min(limit,variants.Count),processed_count=items.Count,created_count=Count("created"),would_create_count=Count("would_create"),skipped_count=Count("skipped"),invalid_count=Count("invalid"),failed_count=failed,dry_run=dryRun,limit},items,failed);}
}
